namespace Pharmacy.Store.Models
{
    public class MockMedicamentRepository : IMedicamentRepository
    {
        private readonly ICategoryRepository _categoryRepository = new MockCategoryRepository();

        public IEnumerable<Medicament> AllMedicaments =>
            new List<Medicament>
            {
                new Medicament {MedicamentId = 1, Name="Strawberry Medicament", Price=15.95M, ShortDescription="Lorem Ipsum", LongDescription="Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake medicament chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon medicament muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart medicament cake danish lemon drops. Brownie cupcake dragée gummies.", Category = _categoryRepository.AllCategories.ToList()[0],ImageUrl="https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysmedicamentshop/fruitmedicaments/strawberrymedicament.jpg", InStock=true, IsDiscountOfTheWeek=false, ImageThumbnailUrl="https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysmedicamentshop/fruitmedicaments/strawberrymedicamentsmall.jpg"},
                new Medicament {MedicamentId = 2, Name="Cheese cake", Price=18.95M, ShortDescription="Lorem Ipsum", LongDescription="Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake medicament chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon medicament muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart medicament cake danish lemon drops. Brownie cupcake dragée gummies.", Category = _categoryRepository.AllCategories.ToList()[1],ImageUrl="https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysmedicamentshop/cheesecakes/cheesecake.jpg", InStock=true, IsDiscountOfTheWeek=false, ImageThumbnailUrl="https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysmedicamentshop/cheesecakes/cheesecakesmall.jpg"},
                new Medicament {MedicamentId = 3, Name="Rhubarb Medicament", Price=15.95M, ShortDescription="Lorem Ipsum", LongDescription="Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake medicament chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon medicament muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart medicament cake danish lemon drops. Brownie cupcake dragée gummies.", Category = _categoryRepository.AllCategories.ToList()[0],ImageUrl="https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysmedicamentshop/fruitmedicaments/rhubarbmedicament.jpg", InStock=true, IsDiscountOfTheWeek=true, ImageThumbnailUrl="https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysmedicamentshop/fruitmedicaments/rhubarbmedicamentsmall.jpg"},
                new Medicament {MedicamentId = 4, Name="Pumpkin Medicament", Price=12.95M, ShortDescription="Lorem Ipsum", LongDescription="Icing carrot cake jelly-o cheesecake. Sweet roll marzipan marshmallow toffee brownie brownie candy tootsie roll. Chocolate cake gingerbread tootsie roll oat cake medicament chocolate bar cookie dragée brownie. Lollipop cotton candy cake bear claw oat cake. Dragée candy canes dessert tart. Marzipan dragée gummies lollipop jujubes chocolate bar candy canes. Icing gingerbread chupa chups cotton candy cookie sweet icing bonbon gummies. Gummies lollipop brownie biscuit danish chocolate cake. Danish powder cookie macaroon chocolate donut tart. Carrot cake dragée croissant lemon drops liquorice lemon drops cookie lollipop toffee. Carrot cake carrot cake liquorice sugar plum topping bonbon medicament muffin jujubes. Jelly pastry wafer tart caramels bear claw. Tiramisu tart medicament cake danish lemon drops. Brownie cupcake dragée gummies.", Category = _categoryRepository.AllCategories.ToList()[2],ImageUrl="https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysmedicamentshop/seasonal/pumpkinmedicament.jpg", InStock=true, IsDiscountOfTheWeek=true, ImageThumbnailUrl="https://gillcleerenpluralsight.blob.core.windows.net/files/bethanysmedicamentshop/seasonal/pumpkinmedicamentsmall.jpg"}
            };

        public IEnumerable<Medicament> DiscountsOfTheWeek
        {
            get
            {
                return AllMedicaments.Where(p => p.IsDiscountOfTheWeek);
            }
        }

        public Medicament? GetMedicamentById(int medicamentId) => AllMedicaments.FirstOrDefault(p => p.MedicamentId == medicamentId);

        public IEnumerable<Medicament> SearchMedicaments(string searchQuery)
        {
            throw new NotImplementedException();
        }
    }
}
