// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pharmacy.Store.Models;

#nullable disable

namespace Pharmacy.Store.Migrations
{
    [DbContext(typeof(PharmacyStoreDbContext))]
    [Migration("20250408125908_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Pharmacy.Store.Models.Category", b =>
            {
                b.Property<int>("CategoryId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                b.Property<string>("CategoryName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("CategoryId");

                b.ToTable("Categories");
            });

            modelBuilder.Entity("Pharmacy.Store.Models.Medicament", b =>
            {
                b.Property<int>("MedicamentId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicamentId"), 1L, 1);

                b.Property<string>("AllergyInformation")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("CategoryId")
                    .HasColumnType("int");

                b.Property<string>("ImageThumbnailUrl")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ImageUrl")
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("InStock")
                    .HasColumnType("bit");

                b.Property<bool>("IsDiscountOfTheWeek")
                    .HasColumnType("bit");

                b.Property<string>("LongDescription")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal>("Price")
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("ShortDescription")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("MedicamentId");

                b.HasIndex("CategoryId");

                b.ToTable("Medicaments");
            });

            modelBuilder.Entity("Pharmacy.Store.Models.Medicament", b =>
            {
                b.HasOne("Pharmacy.Store.Models.Category", "Category")
                    .WithMany("Medicaments")
                    .HasForeignKey("CategoryId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Category");
            });

            modelBuilder.Entity("Pharmacy.Store.Models.Category", b =>
            {
                b.Navigation("Medicaments");
            });
#pragma warning restore 612, 618
        }
    }
}
